name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main  # 或者您要部署的其他分支

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker-compose -f docker-compose.yml build app
          docker-compose -f docker-compose.yml push app

      - name: Deploy to server
        if: success()  # Only run if the previous steps were successful
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          script: |
            # Check if Docker is installed and install it if not
            if ! command -v docker &> /dev/null; then
              echo "Installing Docker..."
              curl -fsSL https://get.docker.com -o get-docker.sh
              sudo sh get-docker.sh
              sudo usermod -aG docker $USER
              newgrp docker
            fi
      
            # Check if Docker Compose is installed and install it if not
            if ! command -v docker-compose &> /dev/null; then
              echo "Installing Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi
            
            if [ ! -d "./repo-directory" ]; then
              git clone https://github.com/your-username/your-repository.git ./repo-directory
            else
              cd ./repo-directory
              git pull
            fi
            cd ./repo-directory
      
            # Login to Docker Hub
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
      
            # Pull the latest images and start the containers
            docker-compose -f docker-compose.yml pull
            docker-compose -f docker-compose.yml up -d
