name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: daxiongya
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: maomaozi/ai-api:latest

      - name: SSH and run Docker image on maozi remote server
        uses: appleboy/ssh-action@master
        with:
          host: ai.mmaozi.com
          username: root
          key: ${{ secrets.REMOTE_SERVER_SSH_KEY }}
          port: 22
          script: |
            docker stop ai-api || true
            docker rm ai-api || true
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username maomaozi --password-stdin
            docker pull maomaozi/ai-api:latest
            docker run -d --net=host --restart=always --name=ai-api -e OPENAI_KEY=${{ secrets.OPENAI_KEY }} -e SPRING_PROFILES_ACTIVE=ai maomaozi/ai-api:latest